### ISSUE TITLE
11.0.2  - LUA error

### ISSUE THREAD

**Issue by Andf** [Draper1/MythicDungeonPortals#20]
Hello!

Receving this error after today's patch:

1x MythicDungeonPortals/MythicDungeonPortals.lua:58: attempt to call global 'GetSpellTexture' (a nil value)
[string "@MythicDungeonPortals/MythicDungeonPortals.lua"]:58: in function <MythicDungeonPortals/MythicDungeonPortals.lua:35>
[string "@MythicDungeonPortals/MythicDungeonPortals.lua"]:141: in function <MythicDungeonPortals/MythicDungeonPortals.lua:125>
[string "@MythicDungeonPortals/MythicDungeonPortals.lua"]:167: in function <MythicDungeonPortals/MythicDungeonPortals.lua:163>
[string "@MythicDungeonPortals/MythicDungeonPortals.lua"]:193: in function <MythicDungeonPortals/MythicDungeonPortals.lua:184>

Locals:
tabFrame = TabFrame {
}
mapIDs = <table> {
 1 = 399
 2 = 400
 3 = 401
 4 = 402
 5 = 403
 6 = 404
 7 = 405
 8 = 406
}
buttonSize = 40
padding = 5
numColumns = 1
topPadding = 35
leftPadding = 20
textOffset = 5
(for state) = <table> {
 1 = 399
 2 = 400
 3 = 401
 4 = 402
 5 = 403
 6 = 404
 7 = 405
 8 = 406
}
(for control) = 1
index = 1
mapID = 399
spellID = 393256
dungeonName = "Ruby Life Pools"
button = Button {
}
row = 0
col = 0
icon = Texture {
}
(*temporary) = nil
(*temporary) = 393256
(*temporary) = "attempt to call global 'GetSpellTexture' (a nil value)"
constants = <table> {
 iconPath = "Interface\Icons\Achievement_ChallengeMode_Gold"
 orderedExpansions = <table> {
 }
 mapIDtoSpellID = <table> {
 }
 myIdToExpansion = <table> {
 }
 mapExpansionToBackground = <table> {
 }
 mapIDtoDungeonName = <table> {
 }
 mapExpansionToMapID = <table> {
 }
}

**Comment by Draper1** [comment]
Looking into this today

**Comment by Draper1** [comment]
Fixed in #21

**Comment by Andf** [comment]
Thanks for the quick fix!
