### ISSUE TITLE
Error on first run, and chat spam after login

### ISSUE THREAD

**Issue by Sythr4l** [Draper1/MythicDungeonPortals#4]
Nice addon!  I received this error the first time i opened the game after installing the addon.  also, everytime I login the addon puts messages in the chat lie "Tab created for Current Season", etc.

1x ...faceMythicDungeonPortals/Minimap/Minimap.lua:37: attempt to index global 'MythicDungeonPortalsSettings' (a nil value)
[string "@MythicDungeonPortals/Minimap/Minimap.lua"]:37: in function <...faceMythicDungeonPortals/Minimap/Minimap.lua:33>
[string "=[C]"]: ?
[string "@Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ceDetails/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ceDetails/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 baseName = "MythicDungeonPortals"
 OnInitialize = <function> defined @MythicDungeonPortals/Minimap/Minimap.lua:33
 Enable = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 Print = <function> defined @Gnosis/Libs/AceConsole-3.0/AceConsole-3.0.lua:50
 EnableModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:464
 GetArgs = <function> defined @Gnosis/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 angle = 45
 icon = <table> {
 }
 UnregisterChatCommand = <function> defined @Gnosis/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 SetEnabledState = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 RegisterChatCommand = <function> defined @Gnosis/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 enabledState = true
 defaultModuleState = true
 Printf = <function> defined @Gnosis/Libs/AceConsole-3.0/AceConsole-3.0.lua:65
 Disable = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 GetName = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleLibraries = <table> {
 }
 SetDefaultModuleState = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 IterateModules = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "MythicDungeonPortals"
 SetDefaultModulePrototype = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 IsEnabled = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 constants = <table> {
 }
 DisableModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
}
(*temporary) = <function> defined @BasicMinimap/Libs/AceDB-3.0/AceDB-3.0.lua:705
(*temporary) = <table> {
 db_registry = <table> {
 }
 frame = Frame {
 }
 New = <function> defined @BasicMinimap/Libs/AceDB-3.0/AceDB-3.0.lua:705
}
(*temporary) = "MythicDungeonPortalsMinimap"
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = "attempt to index global 'MythicDungeonPortalsSettings' (a nil value)"
addon = <table> {
 SetDefaultModuleLibraries = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 baseName = "MythicDungeonPortals"
 OnInitialize = <function> defined @MythicDungeonPortals/Minimap/Minimap.lua:33
 Enable = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 Print = <function> defined @Gnosis/Libs/AceConsole-3.0/AceConsole-3.0.lua:50
 EnableModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:464
 GetArgs = <function> defined @Gnosis/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 angle = 45
 icon = <table> {
 }
 UnregisterChatCommand = <function> defined @Gnosis/Libs/AceConsole-3.0/AceConso

**Comment by Draper1** [comment]
Suspect this is because the SavedVariables don't get initialized properly. Will look into it.

**Comment by Draper1** [comment]
Resolved in #5
